version: '3.9'

services:
  epr-server:
    image: epr-server
    pull_policy: build
    restart: unless-stopped
    depends_on:
      - epr-db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CRYPT_SECRET: "${CRYPT_SECRET}"
      ENFORCE_HTTPS: "${ENFORCE_HTTPS}"
      DB_URI: "mongodb://epr-db/eprdb"
    ports:
      - "${EXTERNAL_SERVER_PORT}:3000"
  epr-db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ${MONGO_DB_VOLUME_PATH}:/data/db